const FETCH_USER_API = 'FETCH_USER_API';
const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export { FETCH_USER_API, FETCH_USER_SUCCESS, FETCH_USER_FAILURE };
